# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.cache/wt [current_project]
set_property parent.project_path /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.srcs/sources_1/imports/new/Register.v
  /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.srcs/sources_1/imports/new/RegisterFile.v
  /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.srcs/sources_1/imports/new/ALU.v
  /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.srcs/sources_1/imports/HW5/opcodes.v
  /home/steven/Desktop/vivado/HW5_pipeline/pipelined_CPU/pipelined_CPU.srcs/sources_1/imports/HW5/cpu.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top cpu -part xc7a200tfbg676-2


write_checkpoint -force -noxdef cpu.dcp

catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
